name: Bug report
description: Report a bug to help us improve trongo
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug.
  - type: input
    id: version
    attributes:
      label: Version
      description: trongo version / commit SHA
      placeholder: 1b1af7c
    validations:
      required: false
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Minimal TRON input and Go snippet to reproduce
      render: text
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: go-version
    attributes:
      label: Go version
      placeholder: go1.21.x
    validations:
      required: false
